//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Player
{
    public Player()
    {
        this.GamePlaySettings = new HashSet<GamePlaySetting>();
        this.GamePlaySettings1 = new HashSet<GamePlaySetting>();
        this.GamePlaySettings2 = new HashSet<GamePlaySetting>();
        this.GamePlaySettings3 = new HashSet<GamePlaySetting>();
    }

    public System.Guid Id { get; set; }
    public string Name { get; set; }
    public string Action { get; set; }
    public string Colour { get; set; }
    public bool HasEarthStoneTreasureStatue { get; set; }
    public bool HasStatueOfTheWindTreasureStatue { get; set; }
    public bool HasCrystalOfFireTreasureStatue { get; set; }
    public bool HasOceansChaliceTreasureStatue { get; set; }
    public Nullable<System.Guid> IslandTileId { get; set; }

    public virtual ICollection<GamePlaySetting> GamePlaySettings { get; set; }
    public virtual ICollection<GamePlaySetting> GamePlaySettings1 { get; set; }
    public virtual ICollection<GamePlaySetting> GamePlaySettings2 { get; set; }
    public virtual ICollection<GamePlaySetting> GamePlaySettings3 { get; set; }
}
